Repository Annoto/moodle-local-js, pull requests merged in 2024-08, with the labels that each got.

#12 Fix snap theme support
  src/interfaces.ts
  src/main.ts
Labels: bug

#13 chore(main): release 1.3.1
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#14 Fix tiles format support
  src/formats/tiles.ts
  src/interfaces.ts
  src/main.ts
  src/util.ts
Labels: bug, enhancement
